final List<Map<String, dynamic>> clothes = [
  {
    "id": 1,
    "name": "Jacket Bloom",
    "color": "Blue",
    "size": "M",
    "location": ["New York", "Warehouse A"],
    "tag": ["winter", "outdoor"],
    "type": "Jacket",
    "price": 89.99,
    // "image": "https://example.com/images/jacket_bloom.jpg"
    "image": "assets/images/c1.png"
  },
  {
    "id": 2,
    "name": "Classic White Tee",
    "color": "White",
    "size": "L",
    "location": ["Los Angeles", "Store 1"],
    "tag": ["casual", "summer"],
    "type": "T-Shirt",
    "price": 19.99,
    "image": "assets/images/c2.png"
  },
  {
    "id": 3,
    "name": "Denim Jeans",
    "color": "Dark Blue",
    "size": "32",
    "location": ["Chicago", "Store 3"],
    "tag": ["denim", "casual"],
    "type": "Jeans",
    "price": 59.50,
    "image": "assets/images/c3.png"
  },
  {
    "id": 4,
    "name": "Athletic Shorts",
    "color": "Black",
    "size": "M",
    "location": ["Miami", "Warehouse B"],
    "tag": ["gym", "sport"],
    "type": "Shorts",
    "price": 29.99,
    "image": "assets/images/c4.png"
  },
  {
    "id": 5,
    "name": "Hoodie Comfort",
    "color": "Gray",
    "size": "L",
    "location": ["Seattle", "Store 2"],
    "tag": ["hoodie", "fall"],
    "type": "Hoodie",
    "price": 49.99,
    "image": "assets/images/c5.png"
  },
  {
    "id": 6,
    "name": "Summer Dress",
    "color": "Floral",
    "size": "S",
    "location": ["San Diego", "Store 4"],
    "tag": ["dress", "summer"],
    "type": "Dress",
    "price": 69.95,
    "image": "assets/images/cardigan.jpg"
  },
  {
    "id": 7,
    "name": "Polo Shirt",
    "color": "Green",
    "size": "M",
    "location": ["Austin", "Warehouse A"],
    "tag": ["smart casual", "polo"],
    "type": "Shirt",
    "price": 34.99,
    "image": "assets/images/eyeglasses.jpg"
  },
  {
    "id": 8,
    "name": "Leather Jacket",
    "color": "Brown",
    "size": "L",
    "location": ["Boston", "Store 5"],
    "tag": ["leather", "biker"],
    "type": "Jacket",
    "price": 129.99,
    "image": "assets/images/menBracelet.jpg"
  },
  {
    "id": 9,
    "name": "Cargo Pants",
    "color": "Khaki",
    "size": "34",
    "location": ["Denver", "Store 3"],
    "tag": ["utility", "outdoor"],
    "type": "Pants",
    "price": 44.95,
    "image": "assets/images/menWatch.jpg"
  },
  {
    "id": 10,
    "name": "Silk Blouse",
    "color": "Cream",
    "size": "M",
    "location": ["San Francisco", "Store 6"],
    "tag": ["formal", "blouse"],
    "type": "Blouse",
    "price": 79.99,
    "image": "assets/images/menClothe.jpg"
  },
  {
    "id": 11,
    "name": "Graphic Tee",
    "color": "Black",
    "size": "L",
    "location": ["Phoenix", "Store 7"],
    "tag": ["graphic", "casual"],
    "type": "T-Shirt",
    "price": 24.99,
    "image": "assets/images/MenDressPants.jpg"
  },
  {
    "id": 12,
    "name": "Yoga Pants",
    "color": "Dark Gray",
    "size": "S",
    "location": ["Portland", "Warehouse C"],
    "tag": ["yoga", "stretch"],
    "type": "Pants",
    "price": 39.99,
    "image": "assets/images/menWatch2.jpg"
  },
  {
    "id": 13,
    "name": "Fleece Vest",
    "color": "Navy",
    "size": "M",
    "location": ["Las Vegas", "Store 8"],
    "tag": ["fleece", "layer"],
    "type": "Vest",
    "price": 54.99,
    "image": "assets/images/ring.jpg"
  },
  {
    "id": 14,
    "name": "Formal Trousers",
    "color": "Charcoal",
    "size": "36",
    "location": ["Atlanta", "Warehouse B"],
    "tag": ["office", "formal"],
    "type": "Trousers",
    "price": 64.99,
    "image": "assets/images/ring2.jpg"
  },
  {
    "id": 15,
    "name": "Raincoat Light",
    "color": "Yellow",
    "size": "L",
    "location": ["Houston", "Store 9"],
    "tag": ["rain", "spring"],
    "type": "Coat",
    "price": 74.95,
    "image": "assets/images/minimalchainnecklace.jpg"
  },
  {
    "id": 16,
    "name": "Striped Sweater",
    "color": "Red/White",
    "size": "M",
    "location": ["Orlando", "Store 10"],
    "tag": ["knit", "casual"],
    "type": "Sweater",
    "price": 44.99,
    "image": "assets/images/prescriptioneyewear.jpg"
  },
  {
    "id": 17,
    "name": "Linen Shirt",
    "color": "Beige",
    "size": "L",
    "location": ["Philadelphia", "Store 11"],
    "tag": ["linen", "summer"],
    "type": "Shirt",
    "price": 52.99,
    "image": "assets/images/mentshirt1.jpg"
  },
  {
    "id": 18,
    "name": "Puffer Jacket",
    "color": "Olive",
    "size": "XL",
    "location": ["Detroit", "Warehouse D"],
    "tag": ["winter", "puffer"],
    "type": "Jacket",
    "price": 99.95,
    "image": "assets/images/ring2.jpg"
  },
  {
    "id": 19,
    "name": "Running Tights",
    "color": "Black",
    "size": "S",
    "location": ["Charlotte", "Store 12"],
    "tag": ["run", "sport"],
    "type": "Tights",
    "price": 34.50,
    "image": "assets/images/ring.jpg"
  },
  {
    "id": 20,
    "name": "Wool Coat",
    "color": "Camel",
    "size": "M",
    "location": ["Columbus", "Warehouse E"],
    "tag": ["wool", "formal"],
    "type": "Coat",
    "price": 149.99,
    "image": "assets/images/ring2.jpg"
  },
  {
    "id": 21,
    "name": "Knit Sweater",
    "color": "Cream",
    "size": "L",
    "location": "Winter storage box",
    "tag": ["knit", "cozy"],
    "type": "Sweater",
    "price": 65.99,
    "image": "assets/images/menBag1.jpg"
  },
  {
    "id": 22,
    "name": "Swim Trunks",
    "color": "Navy Blue",
    "size": "M",
    "location": "Beach bag",
    "tag": ["swim", "summer"],
    "type": "Shorts",
    "price": 35.50,
    "image": "assets/images/menEarrings2.jpg"
  },
  {
    "id": 23,
    "name": "Flannel Shirt",
    "color": "Red/Black Check",
    "size": "XL",
    "location": "Cabin wardrobe",
    "tag": ["flannel", "casual"],
    "type": "Shirt",
    "price": 42.75,
    "image": "assets/images/menSneaker1.jpg"
  },
  {
    "id": 24,
    "name": "Silk Scarf",
    "color": "Emerald Green",
    "size": "One Size",
    "location": "Accessory drawer",
    "tag": ["accessory", "formal"],
    "type": "Scarf",
    "price": 28.99,
    "image": "assets/images/menscarf1.jpg"
  },
  {
    "id": 25,
    "name": "Baseball Cap",
    "color": "Black",
    "size": "Adjustable",
    "location": "Car glove compartment",
    "tag": ["cap", "casual"],
    "type": "Hat",
    "price": 22.50,
    "image": "assets/images/menBelt1.jpg"
  }
];
